### ISSUE TITLE
Not Showing on Options Menu

### ISSUE THREAD

**Issue by CyberRubyFox** [MickeyPickey/Copybara#1]
Is no longer showing up in the Addons options menu as of 11.0.2 (08/13/24)

Error as follows:
```
1x Copybara/Copybara.lua:4: attempt to call global 'GetAddOnMetadata' (a nil value)
[string "@Copybara/Copybara.lua"]:4: in main chunk

Locals:
TocName = "Copybara"
Env = <table> {
 Addon = <table> {
 }
}
Copybara = <table> {
 modules = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 name = "Copybara"
 orderedModules = <table> {
 }
 enabledState = true
 defaultModuleState = true
}
(*temporary) = nil
(*temporary) = "Copybara"
(*temporary) = "Title"
(*temporary) = "attempt to call global 'GetAddOnMetadata' (a nil value)
```

**Comment by LiMiToDriGe** [comment]
Hi, I had the same issue as you and find a fix. I don't know if the development of this addon is still active but I will share the fix here.

To fix this you need to edit the file _Copybara.lua_ in the following folder _World of Warcraft\\\_retail\_\Interface\AddOns\Copybara_ with the folowing:

Line 4:
`Copybara.displayName = C_AddOns.GetAddOnMetadata(TocName, "Title")
`

Line 41:
`         name = format("%s:%s by %s\n\n", GAME_VERSION_LABEL, C_AddOns.GetAddOnMetadata(TocName, "Version"), C_AddOns.GetAddOnMetadata(TocName, "Author")),
`

Hope it will fix your issue.

**Comment by CyberRubyFox** [comment]
That worked like a charm, thanks! Referenced this from the CurseForge page for others to hopefully find because this GitHub took a bit to find.

**Comment by rhaiv** [comment]
Just for fun, I fixed this in a PR for all 3 game versions and updated the ToC files so it loads without loading out-of-date addons. We shall see if it gets merged.

https://github.com/MickeyPickey/Copybara/pull/2
